"""When a turn writes its own version of a script a skill already ships.

Measured, and the reason this signal exists: asked which factor drives
`defect_rate`, the agent loaded `data-analyst`, read SEVEN of its reference
docs, ran `python scripts/premodel_audit.py …` — which cannot work, because a
skill's files are served through the skill tools rather than the filesystem —
and then wrote its own pandas analysis. The answer was correct. Nothing in the
transcript said that none of the six vetted diagnostics had run.

Fixing the invocation (prompt + a redirect on the failure) is the first-order
job. This is the backstop for when it is ignored anyway: the turn should not be
able to assert a result while quietly standing on its own reimplementation.

Why not tighten the skill's verify contract instead — its text says
"scripts/premodel_audit.py, or the equivalent inline" — that text is VENDORED
from upstream, so a local edit diverges and is overwritten on the next
re-vendor. This lives on our side and covers every skill.

Run: ADK_CC_SKIP_DOTENV=1 .venv/bin/python tests/test_skipped_shipped_script.py
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "agents"))
os.environ.setdefault("ADK_CC_SKIP_DOTENV", "1")
os.environ.setdefault("ADK_CC_SKIP_CONFIG_CHECK", "1")
os.environ.setdefault("ADK_CC_API_KEY", "sk-dummy-for-tests")

from adk_cc.tools.bash.tool import _skill_script_hint  # noqa: E402
from adk_cc.verification.signals import collect, nudge_text  # noqa: E402


class _FC:
    def __init__(self, name, args):
        self.name, self.args = name, args


class _FR:
    def __init__(self, name, response):
        self.name, self.response, self.id = name, response, "c1"


class _Part:
    def __init__(self, *, call=None, resp=None, text=None):
        self.function_call, self.function_response, self.text = call, resp, text
        self.thought = False


class _Content:
    def __init__(self, parts):
        self.parts = parts


class _Ev:
    def __init__(self, parts, author="coordinator"):
        self.content, self.author, self.partial = _Content(parts), author, False
        self.long_running_tool_ids = None


# The REAL hint, generated by the bash tool, so the signal and the message
# cannot drift apart: if someone rewords the hint, this test fails.
_HINT = _skill_script_hint(
    "python scripts/premodel_audit.py data.csv --target defect_rate",
    "python: can't open file '/tmp/p/scripts/premodel_audit.py': "
    "[Errno 2] No such file or directory",
)


def _bash_fail(stderr):
    return _Part(resp=_FR("run_bash", {"exit_code": 2, "stdout": "", "stderr": stderr}))


def test_the_measured_case_fires() -> None:
    assert _HINT and "data-analyst" in _HINT, _HINT
    sig = collect([_Ev([
        _Part(call=_FC("load_skill", {"skill_name": "data-analyst"})),
        _Part(call=_FC("run_bash", {"command": "python scripts/premodel_audit.py data.csv"})),
        _bash_fail(_HINT + "\n\npython: can't open file"),
        _Part(call=_FC("run_bash", {"command": "python - <<'PY'\nimport pandas\nPY"})),
        # A lead claim, the shape the signal keys on ("Done — …", "Created …").
        _Part(text="Done — pressure is the driver, correlation 0.99."),
    ])])
    assert sig.bypassed_skill_scripts == ("data-analyst",), sig.bypassed_skill_scripts
    assert sig.skipped_a_shipped_script, sig.summary()
    text = nudge_text(sig)
    assert text and "data-analyst" in text and "run_skill_script" in text, text
    print("OK the_measured_case_fires")


def test_running_it_properly_clears_the_signal() -> None:
    """A first attempt down the wrong road is fine — the redirect exists for
    exactly that. What matters is whether the script ended up running."""
    sig = collect([_Ev([
        _Part(call=_FC("run_bash", {"command": "python scripts/premodel_audit.py x.csv"})),
        _bash_fail(_HINT),
        _Part(call=_FC("run_skill_script", {"skill_name": "data-analyst",
                                            "file_path": "scripts/premodel_audit.py"})),
        _Part(text="Done — pressure is the driver."),
    ])])
    assert sig.ran_skill_scripts == ("data-analyst",)
    assert not sig.skipped_a_shipped_script
    print("OK running_it_properly_clears_the_signal")


def test_saying_so_clears_it_too() -> None:
    """The nudge asks for the script OR an honest note. Both are acceptable
    outcomes, and the second must not be punished."""
    sig = collect([_Ev([
        _Part(call=_FC("run_bash", {"command": "python scripts/premodel_audit.py x.csv"})),
        _bash_fail(_HINT),
        _Part(text="Done — pressure is the driver. Note: the bundled probe "
                   "could not run here, so this is my own analysis and is "
                   "untested against it."),
    ])])
    assert not sig.skipped_a_shipped_script
    print("OK saying_so_clears_it_too")


def test_no_claim_no_nudge() -> None:
    """Exploring without asserting anything is not a violation."""
    sig = collect([_Ev([
        _Part(call=_FC("run_bash", {"command": "python scripts/premodel_audit.py x.csv"})),
        _bash_fail(_HINT),
        _Part(text="That path does not exist; let me look at what the skill ships."),
    ])])
    assert not sig.skipped_a_shipped_script
    print("OK no_claim_no_nudge")


def test_an_unrelated_failure_does_not_fire() -> None:
    """Narrowness: only a turn that ATTEMPTED a skill's script qualifies, so a
    skill whose scripts are genuinely optional never trips this."""
    sig = collect([_Ev([
        _Part(call=_FC("load_skill", {"skill_name": "prd-writer"})),
        _Part(call=_FC("run_bash", {"command": "ls nope"})),
        _bash_fail("ls: nope: No such file or directory"),
        _Part(text="Done — wrote the PRD."),
    ])])
    assert sig.bypassed_skill_scripts == ()
    assert not sig.skipped_a_shipped_script
    print("OK an_unrelated_failure_does_not_fire")


def test_a_different_skills_script_still_counts() -> None:
    """Running skill B's script does not excuse skipping skill A's."""
    sig = collect([_Ev([
        _Part(call=_FC("run_bash", {"command": "python scripts/premodel_audit.py x.csv"})),
        _bash_fail(_HINT),
        _Part(call=_FC("run_skill_script", {"skill_name": "web-smoke-check",
                                            "file_path": "scripts/smoke_page.py"})),
        _Part(text="Done — pressure is the driver."),
    ])])
    assert sig.skipped_a_shipped_script, sig.summary()
    print("OK a_different_skills_script_still_counts")


def main() -> None:
    test_the_measured_case_fires()
    test_running_it_properly_clears_the_signal()
    test_saying_so_clears_it_too()
    test_no_claim_no_nudge()
    test_an_unrelated_failure_does_not_fire()
    test_a_different_skills_script_still_counts()
    print("\nall skipped-shipped-script tests passed")


if __name__ == "__main__":
    main()
